## Aula de numpy

In [44]:
import numpy as np 

In [45]:
print("versao numpy:", np.__version__)

versao numpy: 2.3.2


In [46]:
array_1 = np.array([1,2,3])
array_2 = np.array([[1,2,3],[4,5,6]])

print("Array 1:", array_1)
print("Array 2:\n", array_2)

Array 1: [1 2 3]
Array 2:
 [[1 2 3]
 [4 5 6]]


### Propriedades dos NDarrays

In [47]:
print("Formato (shape)")
print("1D", array_1.shape)
print("2D", array_2.shape)
print("Tamanho (size)")
print("1D", array_1.size)
print("2D", array_2.size)
print("Tipo dos dADOS (dtype)")
print("1D", array_1.dtype)
print("2D", array_2.dtype)
print("Numero de dimensoes (ndim)")
print("1D", array_1.ndim)
print("2D", array_2.ndim)

Formato (shape)
1D (3,)
2D (2, 3)
Tamanho (size)
1D 3
2D 6
Tipo dos dADOS (dtype)
1D int64
2D int64
Numero de dimensoes (ndim)
1D 1
2D 2


### Criacao de NDarrays

In [48]:
print("Zeros:\n", np.zeros((2,3)))
print("Uns:\n", np.ones((2,3)))
print("Cheio:\n", np.full((5,5), 42))
print("ARange:\n", np.arange(0,10,2))
print("Linspace:\n", np.linspace(0,1,5))
print("Random:\n", np.random.rand(2,2))

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Uns:
 [[1. 1. 1.]
 [1. 1. 1.]]
Cheio:
 [[42 42 42 42 42]
 [42 42 42 42 42]
 [42 42 42 42 42]
 [42 42 42 42 42]
 [42 42 42 42 42]]
ARange:
 [0 2 4 6 8]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]
Random:
 [[0.48802765 0.94789376]
 [0.67514579 0.6178496 ]]


In [49]:
matriz = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(matriz)
print("Elemento da Linha 1, coluna 2:", matriz[0,1])
print("Primeira linha:", matriz[0])
print("SeguNDA COLUNA :", matriz[:,1])
print("Submatriz linhas 0-1, colunas 1-2:\n", matriz[0:2, 1:3])
print("Ultima linha", matriz[-1])
print('Ultima coluna:', matriz[:, -1])


[[10 20 30]
 [40 50 60]
 [70 80 90]]
Elemento da Linha 1, coluna 2: 20
Primeira linha: [10 20 30]
SeguNDA COLUNA : [20 50 80]
Submatriz linhas 0-1, colunas 1-2:
 [[20 30]
 [50 60]]
Ultima linha [70 80 90]
Ultima coluna: [30 60 90]


### Operacoes em NDarrays

In [50]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print("Soma elemento a elemento:\n", x+y)
print("Multiplica elemento a elemento:\n", x*y)
print("Produto matricial (dot product)\n", x@y)
print("Transposta de X:\n", x.T )
print("Soma total dos elementos\n", np.sum(x))
print("Soma por colunas de x:\n", np.sum(x, axis=0))
print("Soma por linhas de x:\n", np.sum(x, axis=1))

Soma elemento a elemento:
 [[ 6  8]
 [10 12]]
Multiplica elemento a elemento:
 [[ 5 12]
 [21 32]]
Produto matricial (dot product)
 [[19 22]
 [43 50]]
Transposta de X:
 [[1 3]
 [2 4]]
Soma total dos elementos
 10
Soma por colunas de x:
 [4 6]
Soma por linhas de x:
 [3 7]


### Estatistica em NDarrays

In [ ]:
data = np.random.randint(1, 100, size=10)
print("ND array aleatorio", data)
print("Media", np.mean(data))
print("Desvio padrao:", np.std(data))
print("Valor maximo: ", np.max(data))
print("INdice do valor maximo", np.argmax(data))

: 

### Indexacao Booleana e condicional em NDarray

In [52]:
array_  = np.array([10,15,20,25,30])
print("ARRAY: ", array_)
print("Valores maiores que 20:", array_[array_ > 20])
print("Valores pares:", array_[array_ %2==0])

ARRAY:  [10 15 20 25 30]
Valores maiores que 20: [25 30]
Valores pares: [10 20 30]
